### ISSUE TITLE
create the starter spring boot project

### ISSUE THREAD

**Issue by augustogiles** [backend-services/hosp-ms#2]
Use spring intlzr or another tool to create the initial project

**Comment by SamuelRocha2015** [comment]
###  **Start project created.**

**Package structure**

- configs
- controllers
- exceptions
- helpers
- models
    - domains
    - DTOs
- repositories
- services


**Dependencies**

- spring-boot-starter-parent : 2.1.6.RELEASE
- spring-boot-starter-data-mongodb
- spring-boot-starter-web
- lombok
